groups:
  - name: example-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(request_count[1m]) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "More than 10 requests per minute were detected"
